name: Beat when commit has been made

on:
  issue_comment:
    types:
      - created

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
    - name: Is hearbeat issue
      id: is-heartbeat-issue
      run: |
        if [[ '${{ github.event.issue.title }}' =~ ^Request[:space:]heartbeat[:space:]for[:space:](.*)/(.*)$ ]]; then
            echo ::set-output name=data::true
            echo ${BASH_REMATCH[1]}${BASH_REMATCH[2]}
        fi
    - name: Print comment body
      run: echo "$BODY"
      env:
        BODY: ${{ github.event.comment.body }}
    - name: Print issue title
      run: echo "$TITLE"
      env:
        TITLE: ${{ github.event.issue.title }}