name: Beat when commit has been made

on:
  issue_comment:
    types:
      - created

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
    - name: Is hearbeat issue
      id: is-heartbeat-issue
      run: |
        if [[ '${{ github.event.issue.title }}' =~ ^Request[[:space:]]heartbeat[[:space:]]for[[:space:]](.*)/(.*)$ ]]; then
          echo ::set-output name=flag::true
          echo ::set-output name=owner::${BASH_REMATCH[1]}
          echo ::set-output name=name::${BASH_REMATCH[2]}
        fi
    - name: Is beat comment
      id: is-beat-comment
      if: ${{ github.event.comment.body == '#beat' }}
      run: echo ::set-output name=flag::true
    - name: Print
      if: ${{ steps.is-heartbeat-issue.outputs.flag == 'true' && steps.is-beat-comment.outputs.flag == 'true' }}
      run: |
        grep -o -a -m 1 -h -r "owner: {{" /path/to/dir | head -1