name: Like pizza

on:
  issue_comment:
    types:
      - created

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
    - name: $github
      run:   echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}