name: Beat when commit has been made

on:
  issue_comment:
    types:
      - created

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
    - name: Is hearbeat issue
      id: is-heartbeat-issue
      run: |
        if [[ '${{ github.event.issue.title }}' =~ ^Request[[:space:]]heartbeat[[:space:]]for[[:space:]](.*)/(.*)$ ]]; then
          echo "{flag}={true}" >> $GITHUB_OUTPUT
          echo "{owner}={${BASH_REMATCH[1]}}" >> $GITHUB_OUTPUT
          echo "{name}={${BASH_REMATCH[2]}}" >> $GITHUB_OUTPUT
        fi
    - name: Is beat comment
      id: is-beat-comment
      if: ${{ github.event.comment.body == '#beat' }}
      run: echo "{flag}={true}" >> $GITHUB_OUTPUT
    - name: Checkout kevinboss/heartbeat
      if: ${{ steps.is-heartbeat-issue.outputs.flag == 'true' && steps.is-beat-comment.outputs.flag == 'true' }}
      uses: actions/checkout@v3
      with:
        path: 'heartbeat'
    - name: Read latest
      if: ${{ steps.is-heartbeat-issue.outputs.flag == 'true' && steps.is-beat-comment.outputs.flag == 'true' }}
      id: latest
      uses: KJ002/read-yaml@1.6
      with:
        file: 'heartbeat/beats.yaml'
        key-path: '["${{ steps.is-heartbeat-issue.outputs.owner }}", "${{ steps.is-heartbeat-issue.outputs.name }}"]'
    - name: Check if latest must be updated
      if: ${{ steps.is-heartbeat-issue.outputs.flag == 'true' && steps.is-beat-comment.outputs.flag == 'true' }}
      id: latest-must-be-updated
      run: |
        if [[ ${{ steps.latest.outputs.data }} == "" ]] ; then 
          echo "{flag}={true}" >> $GITHUB_OUTPUT
        elif [[ ${{ steps.latest.outputs.data }} < "${{ github.event.comment.created_at }}" ]] ; then 
          echo "{flag}={true}" >> $GITHUB_OUTPUT
        else
          echo "{flag}={false}" >> $GITHUB_OUTPUT
        fi
    - name: Update latest
      if: ${{ steps.latest-must-be-updated.outputs.flag == 'true' }}
      uses: endaft/action-yamler@v1.0.10
      with:
        file: 'heartbeat/beats.yaml'
        path: ${{ steps.is-heartbeat-issue.outputs.owner }}.${{ steps.is-heartbeat-issue.outputs.name }}
        set: ${{ github.event.comment.created_at }}
        get: false
        append: false
    - name: Delete issue
      if: ${{ steps.latest-must-be-updated.outputs.flag == 'true' }}
      uses: vtcaregorodtcev/delete-issue@main
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        issue_node_id: ${{ github.event.issue.node_id }}
    - name: Commit updated files
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        repository: 'heartbeat/'
        commit_message: 'Updated ${{ steps.is-heartbeat-issue.outputs.owner }}.${{ steps.is-heartbeat-issue.outputs.name }} in beat.yaml'
