name: Like pizza

on:
  issue_comment:
    types:
      - created

jobs:
  beat:
    runs-on: ubuntu-latest

    steps:
    - name: Print comment body
      run: echo "$BODY"
      env:
        BODY: ${{ github.event.comment.body }}
    - name: Print issue title
      run: echo "$TITLE"
      env:
        TITLE: ${{ github.event.comment.issue.title }}