name: Check for latest commit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      hearts-matrix: "${{ steps.hearts.outputs.matrix }}"
    steps:
      - name: Checkout kevinboss/heartbeat
        uses: actions/checkout@v3
      - uses: nahsi/files-to-matrix@v1
        id: hearts
        with:
          files: hearts/**
          settings: >-
            [
              {
                "name": "heart",
                "level": 1
              }
            ]

  check:
    runs-on: ubuntu-latest
    if: needs.matrix.outputs.hearts-matrix
    needs: matrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        hearts: "${{ fromJSON(needs.matrix.outputs.hearts-matrix) }}"

    steps:
      - name: Checkout kevinboss/heartbeat
        uses: actions/checkout@v3
        with:
          path: 'heartbeat'
      - name: Read owner from ${{ matrix.hearts.heart }}
        id: owner
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["owner"]'
      - name: Read name from ${{ matrix.hearts.heart }}
        id: name
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["name"]'
      - name: Checkout ${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}
        uses: actions/checkout@v3
        with:
          repository: '${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}'
          path: 'repo'
      - name: Read latest commit date
        id: latest-commit-date
        run: echo "::set-output name=data::$(git -C repo log -1 --date=format:'%Y-%m-%d' --format='%ad')"
      - name: Read latest from ${{ matrix.hearts.heart }}
        id: latest
        uses: KJ002/read-yaml@1.6
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["latest"]'
      - name: Check if latest must be updated
        id: latest-must-be-updated
        run: |
          if [[ ${{ steps.latest.outputs.data }} == "" ]] ; then 
            echo ::set-output name=flag::true
          fi
          if [[ ${{ steps.latest.outputs.data }} < ${{ steps.latest-commit-date.outputs.data }} ]] ; then 
            echo ::set-output name=flag::true
          fi
          if [[ ${{ steps.latest.outputs.data }} >= ${{ steps.latest-commit-date.outputs.data }} ]] ; then 
            echo ::set-output name=flag::false
          fi
      - name: Update latest
        if: ${{ steps.latest-must-be-updated.output.flat == 'true' }}
        uses: endaft/action-yamler@v1.0.5
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          path: latest
          set: ${{ steps.latest-commit-date.outputs.data }}
          get: false
          append: false
      - name: Set global git config
        if: ${{ steps.latest-must-be-updated.output.flat == 'true' }}
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'Kevin Boss'
          email: 'kevin.boss@outlook.com'
          actor: 'kevinboss'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Commit updated files
        if: ${{ steps.latest-must-be-updated.output.flat == 'true' }}
        run: |
          git -C heartbeat pull --no-rebase
          git -C heartbeat add .
          git -C heartbeat commit -m "updated latest for hearts/${{ matrix.hearts.heart }}"
          git -C heartbeat push