name: check for heartbeats

on:
 # schedule:
 # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      hearts-matrix: "${{ steps.hearts.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v3
      
      - uses: nahsi/files-to-matrix@v1
        id: hearts
        with:
          files: hearts/**
          settings: >-
            [
              {
                "name": "heart",
                "level": 1
              }
            ]

  check:
    runs-on: ubuntu-latest
    if: needs.matrix.outputs.hearts-matrix
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        hearts: "${{ fromJSON(needs.matrix.outputs.hearts-matrix) }}"

    steps:
      - name: checkout heartbeat
        uses: actions/checkout@v3
        with:
          path: 'heartbeat'
      - name: read owner
        id: owner
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["owner"]'
      - name: read name
        id: name
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["name"]'
      - name: show
        run: echo "${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}"
      - name: checkout the hearts repo
        uses: actions/checkout@v3
        with:
          repository: '${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}'
          path: 'repo'
      - name: read latest commit date
        id: latest-commit-date
        run: echo "::set-output name=data::$(git -C repo log -1 --date=format:'%Y-%m-%d' --format='%ad')"
      - name: read latest heartbeat
        id: latest
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["latest"]'
      - run: echo ${{ steps.latest.outputs.data }}
      - name: update latest
        if: ${{ steps.latest.outputs.data == null || steps.latest.outputs.data < latest-commit-date.outputs.data }}
        uses: endaft/action-yamler@v1.0.5
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          path: latest
          set: latest-commit-date.outputs.data
          get: false
          append: false