name: check for heartbeats

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      hearts-matrix: "${{ steps.hearts.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v3
      
      - uses: nahsi/files-to-matrix@v1
        id: hearts
        with:
          files: hearts/**
          settings: >-
            [
              {
                "name": "heart",
                "level": 1
              }
            ]

  check:
    runs-on: ubuntu-latest
    if: needs.matrix.outputs.hearts-matrix
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        hearts: "${{ fromJSON(needs.matrix.outputs.hearts-matrix) }}"

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'heartbeat'
      - name: read owner
        id: owner
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["owner"]'
      - name: read name
        id: name
        uses: KJ002/read-yaml@main
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
          key-path: '["name"]'
      - name: show
        run: echo "${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}"
      - uses: actions/checkout@v3
        with:
          repository: '${{ steps.owner.outputs.data }}/${{ steps.name.outputs.data }}'
          path: 'repo'
      - run: cd repo
      - id: latest-commit-date
        run: echo "::set-output name=date::$(git log -1 --date=format:'%Y/%m/%d' --format='%ad')"
      - run: echo ${{ steps.latest-commit-date.outputs.date }}