name: Generate batches

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      hearts-matrix: "${{ steps.hearts.outputs.matrix }}"
    steps:
      - name: Checkout kevinboss/heartbeat
        uses: actions/checkout@v3
      - uses: nahsi/files-to-matrix@v1
        id: hearts
        with:
          files: hearts/**
          settings: >-
            [
              {
                "name": "heart",
                "level": 1
              }
            ]

  check:
    runs-on: ubuntu-latest
    if: needs.matrix.outputs.hearts-matrix
    needs: matrix
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        hearts: "${{ fromJSON(needs.matrix.outputs.hearts-matrix) }}"

    steps:
      - name: Checkout kevinboss/heartbeat
        uses: actions/checkout@v3
        with:
          path: 'heartbeat'
      - name: Read heart 
        id: heart
        uses: the-coding-turtle/ga-yaml-parser@v0.1.2
        with:
          file: 'heartbeat/hearts/${{ matrix.hearts.heart }}'
      - name: Read latest
        id: latest
        uses: KJ002/read-yaml@1.6
        with:
          file: 'heartbeat/beats.yaml'
          key-path: '["${{ steps.heart.outputs.owner }}", "${{ steps.heart.outputs.name }}"]'
      - name: Get bade data
        id: bade-data
        run: |
          if [[ ${{ steps.latest.outputs.data }} == "" ]] ; then 
            echo "label=none" >> $GITHUB_OUTPUT
            echo "color=red" >> $GITHUB_OUTPUT
          elif (( $(( ($(date +%s) - $(date -d ${{ steps.latest.outputs.data }} +%s)) / 86400 )) > 60 )) ; then 
            echo "label=none" >> $GITHUB_OUTPUT
            echo "color=red" >> $GITHUB_OUTPUT
          elif (( $(( ($(date +%s) - $(date -d ${{ steps.latest.outputs.data }} +%s)) / 86400 )) > 30 )) ; then
            echo "label=weak" >> $GITHUB_OUTPUT
            echo "color=orange" >> $GITHUB_OUTPUT
          else
            echo "label=strong" >> $GITHUB_OUTPUT
            echo "color=green" >> $GITHUB_OUTPUT
          fi
      - name: Create destination directory
        run: mkdir -p "heartbeat/badges/"
      - name: Generate labels
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Heartbeat'
          status: ${{ steps.bade-data.outputs.label }}
          color: ${{ steps.bade-data.outputs.color }}
          path: 'heartbeat/badges/${{ steps.heart.outputs.owner }}_${{ steps.heart.outputs.name }}.svg'
      - name: Pull
        run: git -C heartbeat pull
      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          repository: 'heartbeat/'
          commit_message: 'Updated badge for ${{ steps.heart.outputs.owner }}/${{ steps.heart.outputs.name }}'
